### ISSUE TITLE
Announce deprecation of component archive (CA) in favour of CTF

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm#1156]
**Description**
Announce that CAs will be deprecated and only CTF archives will be supported afterwards. The deprecation end date will be set to 2025-06-30.

**Comment by jakobmoellerdev** [comment]
We probably should not (maybe even cannot) deprecate CAs until the command `ocm add resources` supports adding of arbitrary resources into CTFs. This also affects other commands that are related such as `ocm add sources`. We need to make sure that we can use arbitrary OCM References such as `path/to/ctf//path/to/resource:v0.1.0` in these commands as otherwise the only way to add resources is through the component constructor.

**Comment by jakobmoellerdev** [comment]
Result of Discussion with @fabianburth:

1. Commands like `ocm add resource` (that currently only work on component archives) will be deprecated TOGETHER with CAs in general. 
2. As such, all documentation should point towards proper usage of component-constructor.yaml files.

This means that in the end we will also get rid of a few commands and we can unify our behavior to only use component-constructor.yaml like files.

**Comment by morri-son** [comment]
announced in OCM Team's slack channels.
