### ISSUE TITLE
Create Developer Guides for the Library and CLI

### ISSUE THREAD

**Issue by nikimanoledaki** [open-component-model/ocm#125]
This issue is to create a:
- [ ] Developer Guide for the Library
  - First Subtask (Architecture Overview of the library, explanation of some concepts and terms): 
    - https://github.com/open-component-model/ocm/issues/186)
- [ ] Developer Guide for the CLI

Each documentation must provide an architecture overview, explaining the concepts applied and guide through the individual packages and frameworks used.

Additionally, each documentation should contain steps / `make` commands on how to:
- install dependencies
- compile and run locally
- run the linter
- run unit/integration tests e.g. [flux](https://github.com/fluxcd/flux2/blob/main/CONTRIBUTING.md#how-to-run-the-test-suite), [eksctl](https://github.com/weaveworks/eksctl/blob/main/CONTRIBUTING.md#running-the-unit-tests)

Examples:
- [eksctl](https://github.com/weaveworks/eksctl/blob/main/CONTRIBUTING.md#developing-eksctl)
- [helm](https://helm.sh/docs/community/developers/)

**Comment by In-Ko** [comment]
@nikimanoledaki : Priority-wise, I would like to move this back to "New", and rather focus on things related to _endusers_ of the OCM (like creating more / better examples and guides for the OCM usage itself). Meaning I suggest we focus on adoption of OCM rather than getting other developers involved (which seems the focus of this issue here). WDYT ?

**Comment by In-Ko** [comment]
@nikimanoledaki, @jensh007, @mandelsoft : Now that the enduser docu is in a much better shape, we have to start working on the developer documentation. Already now teams are starting to work with the go libraries (and trying to integrate them into other codebases in order to work with component descriptors), but are having a very hard time doing so.

The reason is not necessarily missing documentation about how to set up a suitable dev environment, but a missing architectural documentation of the libraries, and how they work, what the main parts are, how they are structured and so on. So I believe we have to give this topic here high priority, if we want to get more developers on board.

**Comment by In-Ko** [comment]
Updated description of this issue, classified it as epic, moved to Backlog.

**Comment by In-Ko** [comment]
In favour of two separate tasks we have now on the backlog (https://github.com/open-component-model/ocm/issues/186 and https://github.com/open-component-model/ocm/issues/392), I'd close this one.
