### ISSUE TITLE
Error: Cannot add resource config : reference name with base media already exists

### ISSUE THREAD

**Issue by mayankraipure12** [open-component-model/ocm#231]
**What happened**:
error while creating resource on windows
![ocm-windows](https://user-images.githubusercontent.com/120610939/210711787-d616c675-4bf5-4c54-9f3b-6921bdb48d74.png)

**What you expected to happen**:
It should be able to create resource 

**How to reproduce it (as minimally and precisely as possible)**:
Download the zip in windows environment 
[ocm.zip](https://github.com/open-component-model/ocm/files/10349693/ocm.zip)
extract the zip 
on windows machine : keep ocm.exe in c:/users/<username>/go/bin 
try following the instruction on https://ocm.software/docs/guides/getting-started-with-ocm-flux/
once you reach stop creating config.yaml and trying to add resourse , you will get this issue
Once more issue on the windows it doesn't take type: "Artefact" , I had to modify it as Artifact.
**Anything else we need to know**:

**Environment**:
Windows

**Comment by mandelsoft** [comment]
Unfortunately the import file is missing: `config_resource.yaml`

What the error message implies:
- there is at least a resource `deployment`
- this resource uses a reference hint, not shown (in the latest version it is shown)
- the it uses a second resource `config`, which is using the same hint. This is not recommended, because then they will overwrite each other when importing.

Because the hint is now sown (should be a string a double quotes it is an older version. There was an error complaining about empty hints, also.

Maybe, you should try to use the latest version. If the problem still exists, please add the resources file.

**Comment by phoban01** [comment]
@mayankraipure12 is this still an issue or can we close the ticket?

**Comment by jmickey** [comment]
@mayankraipure12 I'm just going through the bugs in the backlog and was wondering if this ticket could be closed?

**Comment by In-Ko** [comment]
@mayankraipure12 Same here, was going through the issues to close the ones which are not relevant anymore / have been fixed already. What about this one ? Is this still reproducible with the latest OCM CLI version ? Please confirm.

**Comment by mandelsoft** [comment]
The reference hint is used to generate artifact  identities again, after a transport of the content into another repository. (For example provide OCI images, again)

Therefore those names must be unique (at least in the context of a component version), to avoid overwriting the same artifact,
This error tells you that the same name is used at least twice in your component version.

For resources not intended to be propagated to artifact repositories (I think in your example this is not intended), the reference can just be omitted.

**Comment by mayankraipure12** [comment]
Closing this since it is working on windows now
