### ISSUE TITLE
Requesting a working guide for modelling multi component and its deployment via ocm-controller.  

### ISSUE THREAD

**Issue by sidhishruti22** [open-component-model/ocm#285]
**What would you like to be added**:
- Needed the example guide or documentation, The documentation should describe, how to model a component consisting of several child components.
- It should be added in https://ocm.software/docs/guides/getting-started-with-ocm-flux/ .

**Why is this needed**:
-  For the deployment of multiple OCM components with root - reference (parent-child) approach  .
-  We need example for better understanding the relations between parent and child component through "reference.yaml" .
-  Using root - reference approach , there are separate component descriptors has been created for each component , and there is a component descriptors for parent as well, we need to understand how it is getting referenced .
-  And how ocm - controller will pick the child components , if parent componentversion.yaml is getting deployed on cluster ? .

**Comment by In-Ko** [comment]
Please check out https://github.com/open-component-model/ocm-examples/tree/main/kubernetes/podify-walkthrough#open-component-model-podify-tutorial and see whether this might be the Guide / Tutorial / Example you are looking for.
Looking at the requirements you mention above, it seems to tick all the boxes:
- It describes how to model and deploy a component consisting of several child components (in the sense of "referenced components")
- The guide contains explanations around how to model and deploy such an applications

I'd really like to see that if something is missing or not working in the official podinfo example, we work together on improvements for this example rather than inventing a new one. There might even be several "versions" of this example one with Helm, one without, ...) down the road.

**Comment by jensh007** [comment]
Closing this after no additional feedback.
