### ISSUE TITLE
stale URL in README

### ISSUE THREAD

**Issue by ccwienk** [open-component-model/ocm#821]
# Bug Description

README file in root-level of https://github.com/open-component-model/ocm contains reference to `https://ocm.software/spec/` - which is a stale reference.

# Suggestion to prevent future regressions

Use framework with explicit handling of cross-references to detect such stale links (e.g. https://www.sphinx-doc.org/en/master/) and establish build pipeline as part of deployment. Generate README from build, validate all cross-references.

**Comment by morri-son** [comment]
@ccwienk bug fixed with https://github.com/open-component-model/ocm/pull/822.

As it is currently not planned to change the way we create documentation inside of the code repositories, we won't introduce a framework for documentation generation based on source texts, but keep creating markdown files directly.

But your proposal to prevent broken links in the future is very valid. Therefore I created issue https://github.com/open-component-model/ocm-project/issues/214 to add a GitHub action that checks for dead links. All developers are also called to use existing check tools for markdown files inside their IDE and I will stress on that again in one of our next calls.

**Comment by ccwienk** [comment]
There are again stale URLs in README:
- https://github.com/open-component-model/ocm/blob/main/docs/ocm/model.md#artifacts
- https://github.com/open-component-model/ocm/blob/main/docs/ocm/model.md#repositories
- https://github.com/open-component-model/ocm-spec/tree/main/doc/specification/elements

As stated before, I strongly suggest to convert all involved documents to a tool capable of validating cross-references (ideally also external ones), such as sphinx, to avoid future regressions.

**Comment by morri-son** [comment]
created https://github.com/open-component-model/ocm/pull/837 to get this fixed.
